name: multiperson
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - asn1crypto=1.2.0=py37_0
  - blas=1.0=mkl
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py37_0
  - cffi=1.13.0=py37h2e261b9_0
  - chardet=3.0.4=py37_1003
  - conda=4.8.2=py37_0
  - conda-package-handling=1.6.0=py37h7b6447c_0
  - cryptography=2.8=py37h1ba5d50_0
  - cudatoolkit=10.0.130=0
  - cython=0.29.15=py37he6710b0_0
  - dbus=1.13.12=h746ee38_0
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - glib=2.63.1=h5a9c865_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.10.0=py37h7918eee_0
  - hdf5=1.10.4=hb1b8bf9_0
  - icu=58.2=h9c2bf20_1
  - idna=2.8=py37_0
  - intel-openmp=2020.0=166
  - jpeg=9b=h024ee3a_2
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - matplotlib-base=3.1.3=py37hef1b27d_0
  - mkl=2020.0=166
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.15=py37ha843d7b_0
  - mkl_random=1.1.0=py37hd6b4f25_0
  - ncurses=6.1=he6710b0_1
  - ninja=1.9.0=py37hfd86e86_0
  - numpy=1.18.1=py37h4f9e942_0
  - numpy-base=1.18.1=py37hde5b4d6_1
  - olefile=0.46=py37_0
  - openssl=1.1.1d=h7b6447c_4
  - pandas=1.0.1=py37h0573a6f_0
  - pcre=8.43=he6710b0_0
  - pip=19.3.1=py37_0
  - pycosat=0.6.3=py37h14c3975_0
  - pycparser=2.19=py37_0
  - pyopenssl=19.0.0=py37_0
  - pyqt=5.9.2=py37h05f1152_2
  - pysocks=1.7.1=py37_0
  - python=3.7.4=h265db76_1
  - pytorch=1.1.0=py3.7_cuda10.0.130_cudnn7.5.1_0
  - pytz=2019.3=py_0
  - qt=5.9.7=h5867ecd_1
  - readline=7.0=h7b6447c_5
  - requests=2.22.0=py37_0
  - ruamel_yaml=0.15.46=py37h14c3975_0
  - scipy=1.4.1=py37h0b6359f_0
  - seaborn=0.10.0=py_0
  - setuptools=41.4.0=py37_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.12.0=py37_0
  - sqlite=3.30.0=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - torchvision=0.3.0=py37_cu10.0.130_1
  - tornado=6.0.3=py37h7b6447c_3
  - tqdm=4.36.1=py_0
  - urllib3=1.24.2=py37_0
  - wheel=0.33.6=py37_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - addict==2.2.1
    - backcall==0.1.0
    - chumpy==0.69
    - cycler==0.10.0
    - decorator==4.4.2
    - freetype-py==2.1.0.post1
    - future==0.18.2
    - imageio==2.8.0
    - ipdb==0.13.2
    - ipython==7.13.0
    - ipython-genutils==0.2.0
    - jedi==0.16.0
    - kiwisolver==1.1.0
    - matplotlib==3.2.0rc3
    - mmcv==0.2.10
    - networkx==2.4
    - opencv-python==4.2.0.32
    - parso==0.6.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==6.1.0
    - prompt-toolkit==3.0.4
    - protobuf==3.11.3
    - ptyprocess==0.6.0
    - pycocotools==2.0.0
    - pyglet==1.5.0
    - pygments==2.6.1
    - pyopengl==3.1.0
    - pyparsing==2.4.6
    - pypng==0.0.20
    - pyrender==0.1.36
    - python-dateutil==2.8.1
    - pywavelets==1.1.1
    - scikit-image==0.16.2
    - tensorboardx==2.0
    - traitlets==4.3.3
    - trimesh==3.5.25
    - wcwidth==0.1.9
    - smplx
    - configargparse
